Remove call to getLexicalDeclContext()->removeDecl
The lexical decl context of the enumerator is always the EnumDecl. The
call used to alter the AST of the enum in ModB causing the following
error when -ast-dump-all is provided.

```
 error: 'MyEnum3' has different definitions in different modules; definition in module 'ModA.ModAFile1' first difference is enum with 1 element
   20 | typedef enum { MyVal_C } MyEnum3;
      |         ^~~~~~~~~~~~~~~~
 note: but in 'ModB' found enum with 0 elements
   20 | typedef enum { MyVal_C } MyEnum3;
```